[project]
name = "menu-designer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "case-converter>=1.2.0",
    "jinja2>=3.1.6",
    "opencv-python>=4.12.0.88",
    "pygame>=2.6.1",
    "pygame-gui>=0.6.14",
]
